/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.41"
    id("org.web3j") version "4.9.0"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    mavenCentral()
    jcenter()
    repositories {
        maven {
            name = "GitHubPackages-PatriciaTrie"
            url = uri("https://maven.pkg.github.com/eierina/patricia-trie")
            credentials {
                username = project.findProperty("gpr.user") as String?
                password = project.findProperty("gpr.key") as String?
            }
        }
        maven { url = uri("https://hyperledger.jfrog.io/artifactory/besu-maven/") }
        maven { url = uri("https://artifacts.consensys.net/public/maven/maven/") }
        maven { url = uri("https://splunk.jfrog.io/splunk/ext-releases-local") }
        maven { url = uri("https://dl.cloudsmith.io/public/consensys/quorum-mainnet-launcher/maven/") }
    }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use experimental kotlin patricia trie implementation
    implementation("eth.eierina.patriciatrie:patricia-trie:1.0.1")

    implementation("org.web3j:core:4.9.0")
    testCompile("org.web3j:web3j-unit:4.9.0")

    testImplementation("org.junit.jupiter:junit-jupiter:5.8.0")

    // Use the Kotlin test library.
    //testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    //testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

tasks.withType<Test> {
    useJUnitPlatform()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions.jvmTarget = "1.8"
}